version: '2.1'
orbs:
  node: circleci/node@4.2.1
jobs:
  test:
    executor:
      name: node/default
      tag: '15.14.0'
    steps:
      - checkout
      - run:
          name: Check node version
          command: node --version
      - node/install-npm:
          version: '7.13.0'
      - run:
          name: Check npm version
          command: npm --version
      - node/install-packages
      - run:
          name: Build code
          command: npm run build --verbose
      - run:
          name: Run tests
          command: npm run test -- --verbose --ci --runInBand
      - store_test_results:
          path: ./reports/junit/
      - run:
          name: Create chip8-vm dist tarball
          command: tar -cvf chip8-vm-dist.tar ./chip8-vm/dist/
      - run:
          name: Create chip8-cli dist tarball
          command: tar -cvf chip8-cli-dist.tar ./chip8-cli/dist/
      - run:
          name: Create reports tarball
          command: tar -cvf reports.tar ./reports/
      - store_artifacts:
          path: ./reports.tar
      - store_artifacts:
          path: ./chip8-vm-dist.tar
      - store_artifacts:
          path: ./chip8-cli-dist.tar

workflows:
  test:
    jobs:
      - test